name: Fleet Guard

on:
  pull_request:

permissions: {}

concurrency:
  group: "fleet-guard-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  guard:
    name: Guard
    permissions:
      contents: read
    uses: starhaven-io/.github/.github/workflows/reusable-fleet-guard.yml@88150ac7474160e9a5af7771c342ca7f63c3ff10 # v2026.10.05.2
    with:
      repo-name: ${{ github.event.repository.name }}
