name: Link Check

on:
  schedule:
    - cron: "0 14 * * 1" # every Monday at 14:00 UTC
  workflow_dispatch:

permissions: {}

concurrency:
  group: "link-check"
  cancel-in-progress: true

jobs:
  lychee:
    name: Check links
    permissions:
      contents: read
    uses: starhaven-io/.github/.github/workflows/reusable-link-check.yml@03a3794cb337d13703059eb02b44a8d419833ebd # v2026.07.08.1
    with:
      args: "--config lychee.toml --root-dir dist/client './dist/client/**/*.html' README.md"
      build-site: true
      site-directory: ""
      authenticated-github: false
