name: pinprick audit

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main

concurrency:
  group: "pinprick-audit-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  audit:
    name: Audit
    permissions:
      contents: read
      security-events: write # required to upload SARIF results
    uses: starhaven-io/.github/.github/workflows/reusable-pinprick-audit.yml@7917b6404c4b6e9f2bffc8aa4f6b508d06edb897 # v2026.07.29.1
    with:
      advanced-security: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
      fail-on-findings: true
