name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

concurrency:
  group: "zizmor-${{ github.ref }}"
  cancel-in-progress: false

permissions: {}

jobs:
  zizmor:
    name: Analyze
    permissions:
      contents: read
      security-events: write # required to upload SARIF results
    uses: starhaven-io/.github/.github/workflows/reusable-zizmor.yml@1f76a911b7f4fea29eca5983901fa203f38bd303 # v2026.07.27.1
