name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

concurrency:
  group: "zizmor-${{ github.ref }}"
  cancel-in-progress: false

permissions: {}

jobs:
  zizmor:
    name: Analyze
    permissions:
      contents: read
      security-events: write # required to upload SARIF results
    uses: starhaven-io/.github/.github/workflows/reusable-zizmor.yml@17ee5cc7f6fe6aa30883a54f7d890dd8908e250a # v2026.10.08.1
