name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

concurrency:
  group: "zizmor-${{ github.ref }}"
  cancel-in-progress: false

permissions: {}

jobs:
  zizmor:
    name: Analyze
    permissions:
      contents: read
      security-events: write # required to upload SARIF results
    uses: starhaven-io/.github/.github/workflows/reusable-zizmor.yml@5684a11c4f6cbcea9c0fc24fdd5bb6bd602e32c3 # v2026.07.05.8
